name: DPZones
main: io.github.teamsweq.dpzones.DPZones
version: 1.1
commands:
  switch:
    description:
    permission: dpzones.switch
    permission-message: You're spectating!
  spectate:
    description:
    permission: dpzones.spectate
    permission-message: You can’t do that!
  team:
    description:
    permission: dpzones.team
    permission-message: You're spectating!
  join:
    description:
    permission: dpzones.join
    permission-message: You have no power here!
  classes:
    description:
    permission: dpzones.classes
    permission-message: You’re spectating!
  heavy:
    description:
    permission: dpzones.heavy
    permission-message: This class is premium!
  archer:
    description:
    permission: dpzones.archer
    permission-message: This class is premium!
  medic:
    description:
    permission: dpzones.medic
    permission-message: This class is premium!
  soldier:
    description:
    permission: dpzones.soldier
    permission-message: This class is premium!