name: DPZones
main: io.github.teamsweq.dpzonesv2.DPZones
version: 1.1
commands:
  switch:
    description:
    permission: dpzones.switch
    permission-message: You're spectating!
  spectate:
    description:
    permission: dpzones.spectate
    permission-message: You can’t do that!
  team:
    description:
    permission: dpzones.team
    permission-message: You're spectating!
  class:
    description:
    permission: dpzones.class
    permission-message: You’re spectating!
  classes:
    description:
    permission: dpzones.class
    permission-message: You’re spectating!
  kit:
    description:
    permission: dpzones.class
    permission-message: You’re spectating!
  kits:
    description:
    permission: dpzones.class
    permission-message: You’re spectating!
  heavy:
    description:
    permission: dpzones.free
    permission-message: This class is premium!
  archer:
    description:
    permission: dpzones.free
    permission-message: This class is premium!
  medic:
    description:
    permission: dpzones.free
    permission-message: This class is premium!
  soldier:
    description:
    permission: dpzones.free
    permission-message: This class is premium!