name: DPZones
main: io.github.teamsweq.dpzones.DPZones
version: 1.1
commands:
  team:
    description: Team
    permission-message: You're spectating!
  spectate:
    description: Spectate
    permission-message: You can’t do that!
  heavy:
    description: Heavy
    permission-message: This class is premium!
  archer:
    description: Archer
    permission-message: This class is premium!
  medic:
    description: Medic
    permission-message: This class is premium!
  soldier:
    description: Soldier
    permission-message: This class is premium!