name: DPZones
main: io.github.teamsweq.dpzones.DPZones
version: 1.1
commands:
  switch:
    description:
    permission: dpzones.switch
    permission-message: You're spectating!
  spectate:
    description:
    permission: dpzones.spectate
    permission-message: You can’t do that!
  team:
    description:
    permission: dpzones.team
    permission-message: You're spectating!
  heavy:
    description:
    permission: dpzones.heavy
    permission-message: This class is premium!