name: Zones
main: com.gmail.jjfent.zones.Zones
version: 1.1
commands:
  switch:
    description:
    permission: zones.switch
    permission-message: This game isn’t set up for you to do this!
  team:
    description:
    permission: zones.team
    permission-message: You don’t have a team!
  spectate:
    description:
    permission: zones.spectate
    permission-message: Only special players can do this!
  classes:
    description:
    permission: zones.classes
    permission-message: This game isn’t set up for you to do this!
  heavy:
    description:
    permission: zones.heavy
    permission-message: This is a premium class!
  archer:
    description:
    permission: zones.archer
    permission-message: This is a premium class!