name: Zones
main: com.gmail.jjfent.zones.Zones
version: 1.1
commands:
  switch:
    description:
    permission: zones.switch
    permission-message: You're spectating!
  team:
    description:
    permission: zones.team
    permission-message: You're spectating!
  spectate:
    description:
    permission: zones.spectate
    permission-message: Only special players can do this!
  classes:
    description:
    permission: zones.classes
    permission-message: You're spectating!
  heavy:
    description:
    permission: zones.heavy
    permission-message: You're spectating!
  archer:
    description:
    permission: zones.archer
    permission-message: You're spectating!
